### ISSUE TITLE
Hyprland 0.4 support

### ISSUE THREAD

**Issue by seratg** [ItsDrike/hyprland-dwindle-autogroup#13]
After updating to hyprland 0.4, the plugin doesn't seem to be working.

Cheers.

**Comment by ItsDrike** [comment]
Hi, thanks for reporting this, I've been aware of it for a while, just haven't had time to investigate it before. 

After bisecting, I was able to track this down to [`bca7804b`](https://github.com/hyprwm/Hyprland/commit/bca7804bb6e1bf5ce5a99b9ae4806be25e36993c), where vaxry completely rewrote CWindow pointers to make them memory safe, breaking all plugins in the process.

I did attempt to fix it, but I'm not very familiar with smart pointers in C++ and this breaks pretty much all functions in the plugin, as we use `CWindow` a lot, so there's dozens of errors. That means this will likely require a significant rewrite. If you feel up to it, I will accept a PR with a fix, otherwise, this will probably take a while.

**Comment by seratg** [comment]
I see, thanks for the hints!

I could probably look into it on  the weekend.

Cheers.

**Comment by ItsDrike** [comment]
Hey, after some work, I managed to push f526bed, which at least gets the plugin to build with 0.40.0, however it's far from usable. 

The grouping behavior sometimes just doesn't work. This is consistent for each window where it didn't work. Based on the logs, it seems to be because that window has a `deny` flag set for groupping. However, this flag shouldn't be set for it, and when the plugin is unloaded, groupping works, even though this deny flag check is actually only present in Hyprland's original `createGroup` function, which this plugin just calls, so I'm very confused with what's going on with that.

Additionally, while ungroupping with just a single window  does seem to work, if you try and ungroup multiple windows, Hyprland will crash completely. Based on logs, this crash seems to be occuring somewhere in the logic for collecting dwindle nodes, which however doesn't make sense to me, as this logic shouldn't be any different from what it originally was.

Probably just needs some more in depth debugging here, I will take a better look at this at some point, but no promises on when. Of course, if you want, you can still do the PR fixing this, I might get to this before the weekend, but if not, feel absolutely free to tackle it.

**Comment by ItsDrike** [comment]
Sorry for the **really** long wait on this, I pushed several changes which fix the plugin for most hyprland versions, including latest master (although v0.40.0 will remain unsupported, v0.41.0 works and so do all further versions).

**Comment by seratg** [comment]
hey,

thanks a lot for the fix! I have completely forgotten about this, but that's great that it is fixed! Will def start using it again.
