### ISSUE TITLE
crashes on hyprland version 0.27

### ISSUE THREAD

**Issue by structnull** [ItsDrike/hyprland-dwindle-autogroup#4]
Hyprland crash report: https://paste.rs/dvVRL

coredump : https://paste.rs/diOcy

happens randomly or when using togglegroup to ungroup the already grouped windows

hyprland version : 0.27.0 (latest arch release)

**Comment by ItsDrike** [comment]
Hm, I can't seem to reproduce the crash when on hyprland `v0.27.0` git tag.

I don't experience any random crashes, both groupping and ungroupping works without issues. Did you compile the plugin with hyprland v0.27.0 installed? Compiling from a previous versions is not supported and could lead to undefined behavior, as hyprland's ABI is not stable.

If you did, the issue seems to be specific to your machine somehow, could you also submit a hyprland log when the crash happened? See [Hyprland Wiki](https://wiki.hyprland.org/Crashes-and-Bugs/) on how to get it.

Ideally, it'd help a lot if you could also do a `git bisect` on hyprland repo from the previous version you were on (presumabely v0.26.0) and see which commit exactly is causing the crashes.

**Comment by structnull** [comment]
seems like I forgot to recompile  the plugin with the latest version of hyprland 🥲

closing the issue coz im dumb and plugin is working properly

Also thanks for this great plugin and fast response!
