### ISSUE TITLE
New hyprland version breaks the plugin (v0.30.0)

### ISSUE THREAD

**Issue by structnull** [ItsDrike/hyprland-dwindle-autogroup#7]
On the latest hyprland release of version 0.30.0 the plugin can't compile .

``` make all                                                                                                                       main !1  9ms 
g++ -shared -g -fPIC --no-gnu-unique -std=c++23 `pkg-config --cflags pixman-1 libdrm hyprland` -Iinclude -DWLR_USE_UNSTABLE src/main.cpp -o dwindle-autogroup.so
src/main.cpp: In function ‘void moveIntoGroup(CWindow*, CWindow*)’:
src/main.cpp:36:68: error: ‘CHyprGroupBarDecoration’ was not declared in this scope
   36 |         window->m_dWindowDecorations.emplace_back(std::make_unique<CHyprGroupBarDecoration>(window));
      |                                                                    ^~~~~~~~~~~~~~~~~~~~~~~
src/main.cpp:36:92: error: no matching function for call to ‘make_unique<<expression error> >(CWindow*&)’
   36 |         window->m_dWindowDecorations.emplace_back(std::make_unique<CHyprGroupBarDecoration>(window));
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
In file included from /usr/include/c++/13.2.1/memory:78,
                 from /usr/local/include/hyprland/src/plugins/HookSystem.hpp:5,
                 from /usr/local/include/hyprland/src/plugins/PluginAPI.hpp:24,
                 from include/globals.hpp:3,
                 from src/main.cpp:1:
/usr/include/c++/13.2.1/bits/unique_ptr.h:1069:5: note: candidate: ‘template<class _Tp, class ... _Args> constexpr std::__detail::__unique_ptr_t<_Tp> std::make_unique(_Args&& ...)’
 1069 |     make_unique(_Args&&... __args)
      |     ^~~~~~~~~~~
/usr/include/c++/13.2.1/bits/unique_ptr.h:1069:5: note:   template argument deduction/substitution failed:
src/main.cpp:36:92: error: template argument 1 is invalid
   36 |         window->m_dWindowDecorations.emplace_back(std::make_unique<CHyprGroupBarDecoration>(window));
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/c++/13.2.1/bits/unique_ptr.h:1084:5: note: candidate: ‘template<class _Tp> constexpr std::__detail::__unique_ptr_array_t<_Tp> std::make_unique(size_t)’
 1084 |     make_unique(size_t __num)
      |     ^~~~~~~~~~~
/usr/include/c++/13.2.1/bits/unique_ptr.h:1084:5: note:   template argument deduction/substitution failed:
src/main.cpp:36:92: error: template argument 1 is invalid
   36 |         window->m_dWindowDecorations.emplace_back(std::make_unique<CHyprGroupBarDecoration>(window));
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
/usr/include/c++/13.2.1/bits/unique_ptr.h:1094:5: note: candidate: ‘template<class _Tp, class ... _Args> std::__detail::__invalid_make_unique_t<_Tp> std::make_unique(_Args&& ...)’ (deleted)
 1094 |     make_unique(_Args&&...) = delete;
      |     ^~~~~~~~~~~
/usr/include/c++/13.2.1/bits/unique_ptr.h:1094:5: note:   template argument deduction/substitution failed:
src/main.cpp:36:92: error: template argument 1 is invalid
   36 |         window->m_dWindowDecorations.emplace_back(std::make_unique<CHyprGroupBarDecoration>(window));
      |                                                   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~
make: *** [Makefile:26: all] Error 1
```

**Comment by ItsDrike** [comment]
Thanks for reporting this, sorry I took longer to notice this, I've been pretty busy lately with uni.

The bisecting here is pretty annoying, since from commit [`3785de`](https://github.com/hyprwm/Hyprland/commit/3785defaf12b9d99137b2f4c74ab82c51cf733e1), there was a typo in Vector2D.hpp file, making the compilation fail, but for a different reason. This was then only fixed in [`1925e6`](https://github.com/hyprwm/Hyprland/commit/1925e64c21811ce76e5059d7a063f968c2d3e98c), at which point the compilation issue you're encountering was already present.

I wouldn't be surprised if there were other issues in between as well though, as hyprland made a LOT of changes between 0.29.0 and 0.30.0. I will try to fix them all and get the plugin up-to-date with v0.30 though depending on how complex this fix will be, it might be a while until I push a fix for everything. 

I'll try keep you up to date though with any progress on this, if it's a simple fix, I might even be able to get it all done today. But otherwise, it might take me a bit longer. In which case, I'd recommend sticking with v0.29.0 until it's fixed.

**Comment by ItsDrike** [comment]
Should be fixed

**Comment by ItsDrike** [comment]
Btw, if you have some time, I'd love someone to take a look at #8, not necessarily for a code-review, but at least to "play-test" that it works better, and potentially comment on any bugs you encounter, or any changes you'd like made, to improve the experience.

**Comment by structnull** [comment]
> Btw, if you have some time, I'd love someone to take a look at #8, not necessarily for a code-review, but at least to "play-test" that it works better, and potentially comment on any bugs you encounter, or any changes you'd like made, to improve the experience.

Sure ! I'll look into it

**Comment by structnull** [comment]
Also on the latest git it fails to compile with error

```
 g++ -shared -g -fPIC --no-gnu-unique -std=c++23 `pkg-config --cflags pixman-1 libdrm hyprland` -Iinclude -DWLR_USE_UNSTABLE src/main.cpp -o dwindle-autogroup.so
In file included from /usr/local/include/hyprland/src/defines.hpp:1,
                 from /usr/local/include/hyprland/src/Window.hpp:3,
                 from src/main.cpp:3:
/usr/local/include/hyprland/src/includes.hpp:108:10: fatal error: wlr/types/wlr_tearing_control_v1.h: No such file or directory
  108 | #include <wlr/types/wlr_tearing_control_v1.h>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
maybe could be fixed by including the header file (tearing api is introduced recently in hyprland)

**Comment by ItsDrike** [comment]
I couldn't replicate the compilation issue with latest hyprland. It's possible that this was an issue with hyprland itself,  and was fixed in main since. (Possibly here https://github.com/hyprwm/Hyprland/commit/161fee1d8236978eca44efdbede8015763533482).

The other option I see here is that you did something weird and didn't copy `wlr` header files to `/usr/local/include` during compilation. If this is the case, try compiling normally, by cloning the repo and running `sudo make install`, it's possible that this is an issue with the PKGBUILD in the AUR, where the copy instructions just didn't contain this for whatever reason (likely vaxry being lazy and not updating the PKGBUILD).

---

However do note that if you wish to use the plugin on latest Hyprland, I encountered another issue, as Hyprland has changed the permissions of the final binary to 711, meaning non-owners (non-root users) will only have the execute permission over the binary, not a read permission. 

This causes issues with `HyprlandAPI::findFunctionsByName` which relies on `nm` process to read the binary and find a symbol for given function. This plugin uses this function to find the private `CHyprDwindleLayout::getNodeFromWindow(CWindow*)` function. 

As a temporary fix, you can just do `sudo chmod o+r $(which Hyprland)`, making the binary readable to others again. I've already reported this issue on the Hyprland repo though, so hopefully the Makefile will be changed back relatively quickly to fix this. Note that if you're using AUR, this might not affect you at all, since the PKGFILE there should be copying these files manually, so unless vaxry has already updated the permissions there too, you should be fine.

---

If you still can't work it out, consider making a new github issue here, as this one was already marked resolved.
